name: CI/CD para Servico A

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/francisco-paulino-simple/simple-service-a
  INFRA_REPO_URL: https://github.com/francisco-saulino-simple/ci-cd-infra.git

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4
      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_ORG_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "--- Logando no GHCR ---"
            echo ${{ secrets.DOCKER_PAT }} | docker login ghcr.io -u ${{ secrets.DOCKER_ORG_USER }} --password-stdin
            
            INFRA_DIR="/home/deployer/ci-cd-infra"
            
            echo "--- Navegando para a pasta de infra ---"
            cd "$INFRA_DIR"
            
            echo "--- Forçando o download da nova imagem do registro ---"
            # ESTE É O COMANDO CRÍTICO QUE FORÇA A ATUALIZAÇÃO DA IMAGEM
            docker compose pull service-a
            
            echo "--- Recriando o contêiner com a nova imagem ---"
            # O --no-deps garante que apenas o service-a seja recriado
            docker compose up -d --no-deps service-a
            
            echo "--- Limpando imagens antigas ---"
            docker image prune -af